plugins {
    id 'application'
    id 'com.gradleup.shadow'
    id 'io.freefair.lombok'
}

application {
    mainClass = "com.skcraft.launcher.FancyLauncher"
}

repositories {
    maven {
        name = 'mvnrepository'
        url = 'https://repo1.maven.org/maven2/'
    }
    maven{
        name= 'maven_central'
        url = 'https://repo.maven.apache.org/maven2/'
    }
}

dependencies {
    implementation project(path: ':launcher')
    implementation 'com.github.insubstantial:substance:7.3'
    implementation 'com.formdev:flatlaf:3.5.2'
}

shadowJar {
    dependsOn ':launcher:shadowJar'
}
